kafka_connect_config_prefix_path: "{{ kafka_connect_config_prefix.strip('/') }}"
binary_base_path: "{{ '/usr' }}"


#### Kafka Connect Variables ####
kafka_connect_default_service_name: confluent-kafka-connect
kafka_connect_default_config_filename: connect-distributed.properties
kafka_connect_default_user: cp-kafka-connect
kafka_connect_default_group: confluent
kafka_connect_default_log_dir: /var/log/kafka

kafka_connect:
  server_start_file: "{{ binary_base_path }}/bin/connect-distributed"
 # systemd_file: "{{systemd_base_dir}}/{{kafka_connect_service_name}}.service"
 # config_file: "{{ (kafka_connect_config_prefix_path, kafka_connect_config_filename) | path_join }}"
 # systemd_override: /etc/systemd/system/{{kafka_connect_service_name}}.service.d/override.conf
 # log4j_file: "{{ (base_path, 'etc/kafka/connect-log4j.properties') | path_join }}"
 # jaas_file: "{{ (config_base_path, kafka_connect_config_prefix_path, 'connect-jaas.conf' ) | path_join }}"
 # password_file: "{{ (config_base_path, kafka_connect_config_prefix_path, 'connect-password.properties') | path_join }}"
