- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:kafka_connect:akhq
  tasks:
  - import_role:
      name: confluent.common

- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: no
  tags:
    - zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: no
  tags:
    - kafka_broker
  tasks:
  - import_role:
      name: confluent.kafka_broker

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: no
  tags:
    - kafka_connect
  tasks:
  - import_role:
      name: confluent.kafka_connect  

- name: AKHQ Provisioning
  hosts: akhq
  gather_facts: no
  tags:
    - akhq
  tasks:
  - import_role:
      name: akhq